name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
#     - name: docker login
#       env:
#         DOCKER_USER: ${{secrets.DOCKER_USER}}
#         DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
#       run: |
#         echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER
    - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag spaww/prom-aggregation-gateway
      run: docker build . --file Dockerfile --tag spaww/prom-aggregation-gateway:$(date +%s)
      
    - name: Docker Push
      run: docker push spaww/prom-aggregation-gateway
#     steps:
#     - uses: actions/checkout@v3
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag prom-aggregation-gateway:$(date +%s)
